baseURL = 'https://d.oppara.tv/'
title = 'd.oppara.tv'
theme = "PaperMod"

googleAnalytics = "G-YQXP0JM67J"

timeZone = "Asia/Tokyo"
defaultContentLanguage = "ja"
languageCode = 'ja'
hasCJKLanguage = true
pluralizeListTitles = false

[security]
  [security.exec]
    allow = ['^vim$']

[permalinks]
    posts = "/:section/:year/:month/:contentbasename"


[Params]
  author = "oppara"
  dateformat = "2006-01-02"
  hideSummary = true
  disableSpecial1stPost = true
  ShowToc = true
  ShowBreadCrumbs = true
  ShowPostNavLinks = true

[outputs]
home = ["html", "rss", "json"]

[menu]

  [[menu.main]]
    identifier = "search"
    name = "Search"
    url = "/search/"
    weight = 10

  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    weight = 20
